### ISSUE TITLE
Prune Tree function

### ISSUE THREAD

**Issue by zsdqui** [evan-porter/DICOManager#22]
The tree construction uses filters for building the tree, would be useful to have tree pruner to reduce the tree to specified criteria based on a specified nested filter

cohort.prune[False,True,"string"=newCohort, nested_filter=spec]

then the recon can be called on the pruned tree

**Comment by evan-porter** [comment]
I err on the side of not deleting things from trees. So, I think I’ll make it newtree = tree.pull_incomplete(filter) which will create a new tree of the incomplete nodes and return those. The user can then set that newtree = None if they so chose.

The real trick will come with the filter function, where specification of the inclusion of complete, and for what level, constitutes a complete node. So, if you specify modalities of 'CT', 'MR' in the first filter function, do those need to both be included in a Patient, FrameOfReference, Study, etc.

**Comment by evan-porter** [comment]
Added in [commit](https://github.com/BAIRLab/DICOManager/commit/9edf7288b431b61b2126cbec75d16b00f8621c72) with syntax guide updated in tutorial.ipynb to reflect the usage.
