### ISSUE TITLE
Incorrect filter_by case-sensitivity 

### ISSUE THREAD

**Issue by zsdqui** [evan-porter/DICOManager#23]
when cohort.recon is called with filter_by option, no structures are pulled when the structure label has any upper case letters.

For e.g.
Option 1:
```
filter_rt = {'StructName': {'GTV': ['GTV''], 'Ring': ['Ring']}}
cohort.recon(parallelize=True, in_memory=True, path=BUILD, filter_by=filter_rt) 
```

does not work
Option 2:
```
filter_rt = {'StructName': {'GTV': ['GTV','gtv'], 'Ring': ['Ring','ring']}}
cohort.recon(parallelize=True, in_memory=True, path=BUILD, filter_by=filter_rt)
```
however does work, as does 

Option 3:
`cohort.recon(parallelize=True, in_memory=True, path=BUILD) `

Interestingly, in Option 2, the npy dictionary uses the correct case (GTV, Ring) in the labels for the array whereas in Option 3 the labels are (gtv, ring)

**Comment by evan-porter** [comment]
Sure, thats an easy fix. Which branch should I push it to for your workflow?

**Comment by zsdqui** [comment]
dev

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by rlevitin** [comment]
> when cohort.recon is called with filter_by option, no structures are pulled when the structure label has any upper case letters.
> 
> For e.g.
> Option 1:
> ```
> filter_rt = {'StructName': {'GTV': ['GTV''], 'Ring': ['Ring']}}
> cohort.recon(parallelize=True, in_memory=True, path=BUILD, filter_by=filter_rt) 
> ```
> 
> does not work
> Option 2:
> ```
> filter_rt = {'StructName': {'GTV': ['GTV','gtv'], 'Ring': ['Ring','ring']}}
> cohort.recon(parallelize=True, in_memory=True, path=BUILD, filter_by=filter_rt)
> ```
> however does work, as does 
> 
> Option 3:
> `cohort.recon(parallelize=True, in_memory=True, path=BUILD) `
> 
> Interestingly, in Option 2, the npy dictionary uses the correct case (GTV, Ring) in the labels for the array whereas in Option 3 the labels are (gtv, ring)

You sure it's not because of the double apostrophe in Option 1 after `{'GTV': ['GTV'']}`

I'm only a little bit trolling
