### ISSUE TITLE
Change the default branch to main

### ISSUE THREAD

**Issue by rlevitin** [evan-porter/DICOManager#3]
I think this is something you have to do as the owner of the repo

**Comment by rlevitin** [comment]
https://www.hanselman.com/blog/EasilyRenameYourGitDefaultBranchFromMasterToMain.aspx

**Comment by rlevitin** [comment]
@thompa2 you have ownership of the repo, so only you can update the default repo

**Comment by evan-porter** [comment]
Recommended that we change default branch to dev actually, preventing accidental changes to main.

**Comment by thompa2** [comment]
Default Branch Changed to dev. Closing issue.
